// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * @author Felix Zapata.
 * Date: 13/04/2019
 */


/* Assasin class constitutes the second of the concrete classes that
 * derive from Hero. The characteristics of a Assasin are:
 * 1. Attack: High
 * 2. MaxHealthPoints: below average HPs
 * 
 */
public class Assasin extends Hero {
	
	// -------------------------- METHODS --------------------------------/
	
	/**
	 * Class constructor 1
	 */
	public Assasin(String name) {
		// Define the inputs for the superclass
		super("Assasin", name, 40, 60);
		
		// Define the action and set it
		Action myAction = new Attack(this);
		
		// Set action
		this.setMyAction(myAction);
	}

	@Override
	public void performAction(Individual victim) {
		// Perform the action of the Assasin
		
		// The Assasin simply decreases the health of its victim by a parameter
		// given on the performance.
		
		// Re-adapt the health of the victim
		float victimLastHealth = victim.getLastHealth();
		
		// Compute new health
		victimLastHealth -= this.getPerformance();
		
		// Set the new health as the victims lastHealth
		victim.setLastHealth(victimLastHealth);
		
	}

	@Override
	public void retaliate(Individual offender) {
		// Do nothing
	}

	
};
