// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * @author Felix Zapata.
 * Date: 13/04/2019
 */

/* Beserker class constitutes the 5th of the concrete classes that
 * derive from Hero. The characteristics of a Beserker are:
 * 1. Attack: Medium attack
 * 2. MaxHealthPoints: below-average HPs, however it gets heal on kill.
 * (When Beserkers kill a monster, they recover 5 Hps;
 */
public class Beserker extends Hero {
	
	// -------------------------- METHODS --------------------------------/
	
	/**
	 * Class constructor 1
	 */
	public Beserker(String name) {
		// Define the inputs for the superclass
		super("Beserker", name, 20, 60);
		
		// Define the action and set it
		Action myAction = new Attack(this);
		
		// Set action
		this.setMyAction(myAction);
	}

	@Override
	public void performAction(Individual victim) {
		// Perform the action of the Beserker
		
		// The Beserker performs a regular attack like any other HERO with the
		// main difference that he gets health points when he gets a kill;
		
		// Re-adapt the health of the victim
		float victimLastHealth = victim.getLastHealth();
		
		// Compute new health
		victimLastHealth -= this.getPerformance();
		
		// If victimLastHealth updated value is less than 0
		// update the health of the Individual
		float myLastHealth = this.getLastHealth();
		myLastHealth = victimLastHealth <= 0? myLastHealth + 5: myLastHealth;
		
		// Set the new health as of the victim and the Beserker
		victim.setLastHealth(victimLastHealth);
		this.setLastHealth(myLastHealth);
		
	}

	@Override
	public void retaliate(Individual offender) {
		// Do nothing
	}
	
}