// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * @author Felix Zapata
 * Date: 13/04/2019
 * 
 * DonaldTrump class constitutes the 5th of the concrete classes that
 * derive from Monster. The characteristics of a DonaldTrump are:
 * 1. Attack: High
 * 2. MaxHealthPoints: High
 * 
 */
public class DonaldTrump extends Monster {
	
	// -------------------------- METHODS --------------------------------/
	
	/**
	 * Class constructor 1
	 */
	public DonaldTrump(String name) {
		// Define the inputs for the superclass
		super("DonaldTrump", name, 60, 100);
		
		// Define the action and set it
		Action myAction = new Attack(this);
		
		// Set action
		this.setMyAction(myAction);
	}

	@Override
	public void performAction(Individual victim) {
		// Perform the action of the DonaldTrump
		
		// The DonaldTrump simply decreases the health of its victim by a parameter
		// given on the performance.
		
		// Re-adapt the health of the victim
		float victimLastHealth = victim.getLastHealth();
		
		// Compute new health
		victimLastHealth -= this.getPerformance();
		
		// Set the new health as the victims lastHealth
		victim.setLastHealth(victimLastHealth);
		
	}

	@Override
	public String returnClassName() {
		return "DONALDTRUMP";
	}

	@Override
	public boolean willDodgeAttack() {
		return false;
	}

	@Override
	public void retaliate(Individual offender) {
		// Do nothing
	}

	
};
