// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * 
 */
public class Game {
	/**
	 * 
	 */
	public UI ui;
	/**
	 * 
	 */
	public Encounter[] encounter;
	/**
	 * 
	 */
	public User user;
};
