// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * @author Felix Zapata
 * Date: 14/04/2019
 * 
 * GiletJaune class constitutes the 4th of the concrete classes that
 * derive from Monster. The characteristics of GiletJaune are:
 * 1. Attack: Average - , retaliate when hit. 
 *  When GiletJaunes are hit, they hit back the offender that attacked them.)
 * 2. MaxHealthPoints: Low
 */
public class GiletJaune extends Monster {
	
	// -------------------------- METHODS --------------------------------/
	
	/**
	 * Class constructor 1
	 */
	public GiletJaune(String name) {
		// Define the inputs for the superclass 
		super("GiletJaune", name, 20, 40);
		
		// Define the action and set it
		Action myAction = new Attack(this);
		
		// Set action
		this.setMyAction(myAction);
	}

	@Override
	public void performAction(Individual victim) {
		// Perform the action of the GiletJaune
		
		// The GiletJaune simply decreases the health of its victim by a parameter
		// given on the performance.
		
		// Re-adapt the health of the victim
		float victimLastHealth = victim.getLastHealth();
		
		// Compute new health
		victimLastHealth -= this.getPerformance();
		
		// Set the new health as the victims lastHealth
		victim.setLastHealth(victimLastHealth);
		
	}

	@Override
	public void retaliate(Individual offender) {
		// The GiletJaune is the only type of Monster which
		// does retaliates. For such reason execute the action
		// of the GiletJaune to the offender.
		this.getMyAction().execute(offender);
		
	}

	@Override
	public boolean willDodgeAttack() {
		return false;
	}

	@Override
	public String returnClassName() {
		return "GILETJAUNE";
	}


}
