// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * @author Xavi Tio.
 * Date: 13/04/2019
 */

/* Joker class constitutes the 6th of the concrete classes that
 * derive from Monster. The characteristics of a Joker are:
 * 1. Attack: the Joker turns its victims against themselves. Therefore, when
 * a Joker attacks the value of the attack is computed by adding the 
 * Joker attack value (average) plus the attack of its victim.
 * 2. MaxHealthPoints: Average
 * 
 */
public class Joker extends Monster {
	
	// -------------------------- METHODS --------------------------------/
	
	/**
	 * Class constructor 1
	 */
	public Joker(String name) {
		// Define the inputs for the superclass
		super("Joker", name, 20, 70);
		
		// Define the action and set it
		Action myAction = new Attack(this);
		
		// Set action
		this.setMyAction(myAction);
	}

	@Override
	public void performAction(Individual victim) {
		// Perform the action of the Joker
		
		// The Joker simply decreases the health of its victim by the sum of the parameter
		// given on the performance and the parameter given on the performance of its victim.
		
		// Re-adapt the health of the victim
		float victimLastHealth = victim.getLastHealth();
		
		// Compute new health
		victimLastHealth -= this.getPerformance()+victim.getPerformance();
		
		// Set the new health as the victims lastHealth
		victim.setLastHealth(victimLastHealth);
		
	}

	@Override
	public void retaliate(Individual offender) {
		// Do nothing
	}

	
};
