// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

// ---------------------- IMPORT MODULES ----------------------------//

import java.util.ArrayList;

// -----------------------------------------------------------------//

/************************************************************/
/**
 * @author Felix Zapata
 * Date: 13/04/2019
 * 
 * Rogue class constitutes the 4th of the concrete classes that
 * derive from Hero. The characteristics of a Rogue are:
 * 1. Attack: Medium attack, poisons the target 
 * (A poisoned target will lose 3 HPs at the beginning of 
 * its turn up to three times)
 * 2. MaxHealthPoints: Low
 */
public class Rogue extends Hero {
	
	// -------------------------- METHODS --------------------------------/
	
	/**
	 * Class constructor 1
	 */
	public Rogue(String name) {
		// Define the inputs for the superclass
		super("Rogue", name, 50, 67);
		
		// Define the action and set it
		Action myAction = new Attack(this);
		
		// Set action
		this.setMyAction(myAction);
	}

	@Override
	public void performAction(Individual victim) {
		// Rogue is one of the advanced classes and thus its attack is a bit more complex.
		// When performing its attack, Rogue poisons its target, thus the attack
		// spans through 3 turns and the poisoned target will lose 3HPs at the beginning
		// of its turn.
		
		// First get the health ArrayList of the victim
		ArrayList<Float> victimHealth = victim.getHealth();
		
		// Append to it 3 more records with -3 (for the 3 next turns when the health ArrayList is
		// update
		victimHealth.add((float) -3);
		victimHealth.add((float) -3);
		victimHealth.add((float) -3);
	}

	@Override
	public String returnClassName() {
		return "ROGUE";
	}

	@Override
	public boolean willDodgeAttack() {
		return false;
	}

	@Override
	public void retaliate(Individual offender) {
		// Do nothing
	}

}
