// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * 
 */
public class User {
	/**
	 * 
	 */
	private static String name;
	/**
	 * 
	 */
	private undefined team;
};
