// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package MAE1Project;

/************************************************************/
/**
 * @author Felix Zapata
 * Date: 13/04/2019
 * 
 * Warrior class constitutes the first of the concrete classes that
 * derive from Hero. The characteristics of a Warrior are:
 * 1. Attack: Medium
 * 2. MaxHealthPoints: above average Health points.
 * 
 */

public class Warrior extends Hero {
	
	// -------------------------- METHODS --------------------------------/
	
	/**
	 * Class constructor 1
	 */
	public Warrior(String name) {
		// Define the inputs for the superclass
		super("Warrior", name, 67, 50);
		
		// Define the action and set it
		Action myAction = new Attack(this);
		
		// Set action
		this.setMyAction(myAction);
	}

	@Override
	public void performAction(Individual victim) {
		// Perform the action of the Warrior
		
		// The Warrior simply decreases the health of its victim by a parameter
		// given on the performance.
		
		// Re-adapt the health of the victim
		float victimLastHealth = victim.getLastHealth();
		
		// Compute new health
		victimLastHealth -= this.getPerformance();
		
		// Set the new health as the victims lastHealth
		victim.setLastHealth(victimLastHealth);
		
	}

	@Override
	public String returnClassName() {
		return "WARRIOR";
	}

	@Override
	public boolean willDodgeAttack() {
		return false;
	}

	@Override
	public void retaliate(Individual offender) {
		// Since Warrior does not retaliate then this
		// method does nothing
	}
	
}
